### ISSUE TITLE
README example needs -p 8001:8001

### ISSUE THREAD

**Issue by borisovg** [ArchiveTeam/warrior-dockerfile#10]
The README talks about connection to port 8001 for web interface but does mention `-p 8001:8001` that is necessary for this to work.

**Comment by brannondorsey** [comment]
This has been addressed with https://github.com/ArchiveTeam/warrior-dockerfile/pull/13.

**Comment by chfoo** [comment]
Closing because it was fixed in that PR mentioned above.
