### ISSUE TITLE
add info how to persist config, stats, etc.

### ISSUE THREAD

**Issue by Finkregh** [ArchiveTeam/warrior-dockerfile#17]
it would be nice if e.g. the nickname could be stored externally...

**Comment by brandongalbraith** [comment]
@Finkregh What about passing the nickname in as an environment variable? Otherwise, the docker container is going to need to be mounted on the local file system to maintain nickname state.

**Comment by Finkregh** [comment]
env-var should be possible, is that documented somewhere?

**Comment by icco** [comment]
With #26 merged, I'm running a few warriors configured entirely by env vars in kubernetes. Working great so far, so this can probably be closed.
