### ISSUE TITLE
standard_init_linux.go:190: exec user process caused "exec format error" on raspi 3b+

### ISSUE THREAD

**Issue by tomasparks** [ArchiveTeam/warrior-dockerfile#20]
I got docker runing on my rasPi, ran docker pull archiveteam/warrior-dockerfile
and ran docker run -p 8001:8001 archiveteam/warrior-dockerfile
got error message: standard_init_linux.go:190: exec user process caused "exec format error"

> xbmc@xbmc-box:~ $ sudo docker info
> Containers: 0
>  Running: 0
>  Paused: 0
>  Stopped: 0
> Images: 0
> Server Version: 18.04.0-ce
> Storage Driver: overlay2
>  Backing Filesystem: xfs
>  Supports d_type: false
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
> runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
> init version: 949e6fa
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 4.14.34-v7+
> Operating System: Raspbian GNU/Linux 9 (stretch)
> OSType: linux
> Architecture: armv7l
> CPUs: 4
> Total Memory: 976.7MiB
> Name: xbmc-box
> ID: OM4E:GKNA:RCRB:6NTA:FJRM:GNK2:WLMA:SEI4:5QAA:QBKK:XP4Y:XSIA
> Docker Root Dir: /media/vdisk/programs/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> 
> WARNING: overlay2: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
>          Reformat the filesystem with ftype=1 to enable d_type support.
>          Running without d_type support will not be supported in future releases.
> WARNING: No memory limit support
> WARNING: No swap limit support
> WARNING: No kernel memory limit support
> WARNING: No oom kill disable support
> WARNING: No cpu cfs quota support
> WARNING: No cpu cfs period support

**Comment by brannondorsey** [comment]
I too just experienced this. I believe it may be because the docker image has been configured on an x86 architecture and not the armhf arch of a Pi. Can anyone confirm? I'm going to try rebuilding the Dockerfile myself tomorrow with perhaps a few tweeks.

**Comment by brannondorsey** [comment]
Yep, that was it. Fortunately this repo has a Dockerfile specifically for raspberry pi. You can build and run a docker image from it like so:

```bash
# clone the repo
git clone https://github.com/ArchiveTeam/warrior-dockerfile
cd warrior-dockerfile

# build the Dockerfile.raspberry docker image
docker build -f Dockerfile.raspberry -t archiveteam/warrior-dockerfile:rpi .

# create and run the container, re-launching on reboot unless stopped
docker run --detach --publish 8001:8001 --restart unless-stopped archiveteam/warrior-dockerfile:rpi
```

**Comment by Safename321** [comment]
If anyone still has this problem, we have it too in this repo
https://github.com/BrandonJoffe/home_surveillance/issues/54

**Comment by TomGlass** [comment]
https://github.com/ArchiveTeam/warrior-dockerfile/issues/56
