### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by LachlanGytha** [ArchiveTeam/warrior-dockerfile#27]
Is there any way to input proxy settings for this to use? Doesn't need to be multiple proxies, just a single one would be fine.

**Comment by chfoo** [comment]
Proxy settings could be provided but the software (seesaw, wget, etc) might not pick it up because it is intentionally not supported and not recommended. Is there a reason why you need to use a proxy?

**Comment by pazzjurist** [comment]
> Proxy settings could be provided but the software (seesaw, wget, etc) might not pick it up because it is intentionally not supported and not recommended. Is there a reason why you need to use a proxy?

My hosts all get tunneled to a VPN via a proxy server.

**Comment by chfoo** [comment]
In that case, is it possible to transparently route the container network traffic to the VPN somehow? My concern with using a web proxy is that projects are sensitive to the HTTP requests and responses. The archives need to accurately reflect what the web server is sending so if the proxy server strips headers or returns error messages, it will ruin the archives.

**Comment by TomGlass** [comment]
Yeah VPNs/proxies are heavily discouraged, in the event of IP rate limits these days this is counteracted using large amounts of IPs natively or using large amounts of hourly services from the likes of Hetzner Cloud/DigitalOcean
