### ISSUE TITLE
"Project code is out of date and needs to be upgraded. To remedy this problem immediately, you may reboot your warrior"

### ISSUE THREAD

**Issue by rmoriz** [ArchiveTeam/warrior-dockerfile#28]
I'm getting this error now when starting a fresh instance of the docker image and selecting the tumblr project. It just waits and reprints the error message.

**Comment by chfoo** [comment]
This is a Tumblr project issue which issues should be discussed on the IRC channel #tumbledown or on the [tumblr-grab](https://github.com/ArchiveTeam/tumblr-grab) repository. However, as announced on #archiveteam, there was mass bans and there people are working on the Tumblr scripts which is resulting in the error message.

**Comment by rmoriz** [comment]
ah, sorry. Didn't read that. Looks like I'll have to add another PR to re-add the dnsmasq hack. Will open a PR when ready
