### ISSUE TITLE
Not starting on rpi 3b+

### ISSUE THREAD

**Issue by 1nikolas** [ArchiveTeam/warrior-dockerfile#34]
Hello just installed warrior on my rpi 3b+ using the commands provided on readme. After the "pull" command completed successfully I tried to run it but I get no output and port is not open. I left this command running for a lot of time but it stayed the same. Thanks in advance
![image](https://user-images.githubusercontent.com/30593419/54833159-3c468180-4cc6-11e9-993c-26ce27701b44.png)

**Comment by icco** [comment]
Run without detach, what are the logs saying?

**Comment by 1nikolas** [comment]
@icco still don't get any output. Where are the logs located?

**Comment by 1nikolas** [comment]
Oh it took some time here are the logs
`2019-03-23 22:30:16,589 - root - INFO - Logging to /data/data/warrior.log
2019-03-23 22:30:16,592 - seesaw.warrior - ERROR - Error loading config.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/seesaw/warrior.py", line 82, in load
    with open(self.config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/warrior/projects/config.json'
**************************************************************************
*                                                                        *
*   ArchiveTeam Seesaw kit - 0.10.0                                      *
*                                                                        *
**************************************************************************

Starting the web interface on 0.0.0.0:8001...

--------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/run-warrior3", line 13, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/seesaw/script/run_warrior.py", line 97, in main
    keep_data=args.keep_data)
  File "/usr/local/lib/python3.7/dist-packages/seesaw/warrior.py", line 232, in __init__
    self.config_manager.add(self.warrior_id)
  File "/usr/local/lib/python3.7/dist-packages/seesaw/warrior.py", line 62, in add
    self.save()
  File "/usr/local/lib/python3.7/dist-packages/seesaw/warrior.py", line 89, in save
    with open(self.config_file, "w") as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/warrior/projects/config.json'
`

**Comment by icco** [comment]
Ah I just re-read your initial issue. You need to use & build the rpi docker image which is at https://github.com/ArchiveTeam/warrior-dockerfile/blob/master/Dockerfile.raspberry

so in general you will do the following:

```
- git clone https://github.com/ArchiveTeam/warrior-dockerfile
- cd warrior-dockerfile
- docker build -f Dockerfile.raspberry -t watrpi
- docker run watrpi
```

**Comment by 1nikolas** [comment]
I uswd this command. Is it different?

docker build --rm -t warrior-arm32v5:latest -f Dockerfile.raspberry .

**Comment by icco** [comment]
Ah sorry, no it's basically the same. Hmm, I don't have a working rpi, but that's weird that file is being described as a directory.

**Comment by oliviermichaelis** [comment]
Don't you have to bind mount the volumes `/var/local/warrior/data:/data/data` and `/var/local/warrior/config.json:/home/warrior/projects/config.json`?
And create the missing directories beforehand, as well as the `config.json` with `touch /var/local/warrior/config.json`.
Then run the docker container with:
```
docker run \
--volume /var/local/warrior/data:/data/data \
--volume /var/local/warrior/config.json:/home/warrior/projects/config.json \
--publish 8001:8001 \
--restart always \
warrior-arm32v5:latest
```

If you run that with an empty `config.json`, I think the docker container might crash again, but it populates the `config.json`. I think I had to run a new docker container which then worked.

**Comment by 1nikolas** [comment]
@oliviermichaelis Thanks for your answer. I'm not experienced with docker so I have a question. What do the ":" mean in file paths?

**Comment by oliviermichaelis** [comment]
@1nikolas When using `--volume`, you bind mount a file or directory from your host filesystem into the container.
So `--volume /path/in/host/filesystem:/path/in/container/filesystem` indicates the path of the file or directory in the host filesystem and the path in the container filesystem, separated by a `:`.

**Comment by joshghent** [comment]
I think I have a similar issue... I've messed around with chown'ing and chmod'ing the file but got no luck
```
Traceback (most recent call last):
  File "/usr/local/bin/run-warrior3", line 13, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/seesaw/script/run_warrior.py", line 75, in main
    setup_logging(args.data_dir)
  File "/usr/local/lib/python3.7/dist-packages/seesaw/script/run_warrior.py", line 25, in setup_logging
    path, when='D', backupCount=10
  File "/usr/lib/python3.7/logging/handlers.py", line 199, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/usr/lib/python3.7/logging/handlers.py", line 54, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/data/data/warrior.log'
```

**Comment by TomGlass** [comment]
https://github.com/ArchiveTeam/warrior-dockerfile/issues/56
