### ISSUE TITLE
Description on hub has extra -e

### ISSUE THREAD

**Issue by arthurlutz** [ArchiveTeam/warrior-dockerfile#37]
https://hub.docker.com/r/archiveteam/warrior-dockerfile/ command 

```
  docker run \
      --detach \
      --env DOWNLOADER="your name" -e \
      --env SELECTED_PROJECT="auto" \
      --publish 8001:8001 \
      --restart always \
      archiveteam/warrior-dockerfile
```

fails saying `docker: invalid reference format: repository name must be lowercase.` 

the `-e` should be removed (like in the README for this project).

**Comment by TomGlass** [comment]
Issue resolved with https://github.com/ArchiveTeam/warrior-dockerfile/commit/c776abd3438169f20d011538e3ef5e434f6cec8a
