### ISSUE TITLE
Unable to build on Raspberry Pi 4

### ISSUE THREAD

**Issue by ShaunLWM** [ArchiveTeam/warrior-dockerfile#43]
Previously I had warrior working on a vmware and the trouble was that it had to be shut down when I am off to bed. Now that I've got a RPI 4, I can keep it running 24/7. However when trying to build for RPI, there seemed to have some error while running `sudo apt-get update` in the Dockerfile.

```
Step 3/18 : RUN apt-get update
 ---> Running in 8dbb1fd1f43f
Get:1 http://deb.debian.org/debian sid InRelease [153 kB]
Err:1 http://deb.debian.org/debian sid InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://deb.debian.org/debian sid InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian sid InRelease' is not signed.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
```

Looking into https://github.com/debuerreotype/docker-debian-artifacts/issues/101 which seemed to have the same error,

RPI version
`Linux localhost 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux`
Docker
`Docker version 20.10.2, build 2291f61`
As of now, they seemed to have come to a conclusion that it's some building issues
https://github.com/docker-library/docker/issues/260
https://github.com/djmaze/librespot-snapserver/issues/7

May I know if there's any workaround on this end? Thank you!

**Comment by janpaul123** [comment]
Using `FROM arm32v5/debian:stable-slim` instead of `FROM arm32v5/debian:sid-slim` at the top of `Dockerfile.raspberry` fixed it for me.

**Comment by 13rac1** [comment]
@janpaul123 Confirmed this solves the build issue.

Should this change be PR'd?

**Comment by LegendEffects** [comment]
Can confirm this allows the dockerfile to build but I had issues relating to #42 with none of the proposed solutions working.

**Comment by edofullin** [comment]
It seems to be a bigger issue with the raspberry, I've encountered it in other projects as well.

Updating libseccomp2_2 on the host seems to solve it, but I still get errors related to #42

**Comment by edofullin** [comment]
It seems like the dockerfile for the raspberry pi has not been updated for over 2 years and it no longer works (also it build the image for armel insted of armhf which works best on the raspberry pi 3 and 4.

However you can use the new Dockerfile for x86 for armhf as well, you just have to build wget-lua and grab-base-df  for the new architecture.

Then you can just build this image from Dockerfile and it seems to work fine.

**Comment by TomGlass** [comment]
https://github.com/ArchiveTeam/warrior-dockerfile/issues/56

**Comment by ramazansancar** [comment]
I have the same problem on Raspberry pi 4.
Is there a solution for this?

**Comment by TheTechRobo** [comment]
No: see #56
