### ISSUE TITLE
Image on Docker hub is 2 years old

### ISSUE THREAD

**Issue by Freekers** [ArchiveTeam/warrior-dockerfile#45]
The image on Docker hub is 2 years old and as such may contain vulnerabilities or bugs that may have been fixed in newer versions of the included packages. [Additionally, Docker will change their retention policy regarding image expiration on Docker hub mid 2021.](https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/)
Please trigger a new build to be pushed to Docker hub.
Thank you!

**Comment by chfoo** [comment]
I'm not sure who has access to the account, but no one active now has been able to gain access to it. Same reason affecting #37.

**Comment by Freekers** [comment]
I see... How do you suggest we continue?

**Comment by km09** [comment]
Reopening to remind myself to check why that didn't build correctly. 

Simple solution here is to stop using this image unfortunately. The 'warrior' here isn't supported by most new projects these days, and you'd be better suited running the individual containers from each project's repo (example for reddit [here](https://github.com/ArchiveTeam/reddit-grab))

There's stuff in the works to create a new warrior that'll support newer projects, but that's not complete yet.
