### ISSUE TITLE
Recover DockerHub and / or use new Image Repository

### ISSUE THREAD

**Issue by HeroCC** [ArchiveTeam/warrior-dockerfile#49]
Hi everyone,

I see there have been recent pushes to this repo. However, the image uploaded to DockerHub is nearly [two years old](https://hub.docker.com/layers/archiveteam/warrior-dockerfile/latest/images/sha256-742864ef616f0a80bdd162538964c43df677f0912716ebda44605063258a6d18?context=explore). Could someone please update the CI so it gets pushed there as well?

Thanks!

**Comment by HeroCC** [comment]
Ah wait, I see this is a duplicate of #45, my bad. It may be worth contacting the DockerHub folks and asking them to recover the account. Otherwise, could you update documentation to point to a new repo? Maybe something like quay.io or the Github packages? 

I know for a lot of people including myself I'm happy to run the warrior and help out the team, but when things get too complicated I wouldn't be surprised if users are lost.

**Comment by TomGlass** [comment]
tagging @km09 We're currently in the process of doing this :)

**Comment by km09** [comment]
This has been recovered, and a new build has been pushed.
