### ISSUE TITLE
No such image at atdr.meo.ws

### ISSUE THREAD

**Issue by ChadOhman** [ArchiveTeam/warrior-dockerfile#50]
Hello,

Looking to spin up a docker warrior but I'm getting the following error:
`No such image: atdr.meo.ws/archiveteam/warrior-dockerfile:latest`

**Comment by TomGlass** [comment]
Hello,

Please try again this seems to be working fine here

**Comment by ChadOhman** [comment]
Working now, thanks @TomGlass.
