### ISSUE TITLE
data mountpoint is not used?

### ISSUE THREAD

**Issue by jubbens** [ArchiveTeam/warrior-dockerfile#51]
Everything seems to be in order (running on linux x64), but the container doesn't seem to be using the volume I specified for `/data/data` as per the readme. Does the container use this volume only for the arm version?

**Comment by fiergna** [comment]
if you want to store the data on a disk instead of in the docker image, you can find it under /data/projects

**Comment by jubbens** [comment]
After looking at the logs, the path it uses appears to actually be `/home/warrior/data/projects`. Mounting the volume here seems to work correctly. Docs should be updated.
