### ISSUE TITLE
zstandard python module needed 

### ISSUE THREAD

**Issue by billsargent** [ArchiveTeam/warrior-dockerfile#55]
For some projects, such as yahoo answers, zstandard python module is needed. 
I'm working with the raspberry pi docker file. I've had to add python-dev and python3-dev to the apt-get for the container, and also add pip3 install zstandard and pip install zstandard. 

I'm not sure if this is something that needs to be permanent in the docker file or not.

**Comment by jhollowe** [comment]
I've been working on getting a build working on the Pi [here](https://github.com/jhollowe/warrior-dockerfile/tree/raspi-update) but have pause on this repo to work on implementing multiarch builds for the requisite repos/tools.

Ultimately, it would be great to split the Dockerfile into two steps to have a build step and a final step which only copies in the built tools from the builder step ([docker multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/))

**Comment by billsargent** [comment]
I seem to be stuck now with no working wget+at errors. Everything compiles as normal though, including wget. So there must be something else going on inside the container.

**Comment by TomGlass** [comment]
Hello guys,

We're not supporting ARM right now. We are working to develop a new version but we do need to do thorough testing on the various components including the different variants of wget-at we use. Please do not test that version on live projects @jhollowe due to possible garbage data being produced

**Comment by TomGlass** [comment]
https://github.com/ArchiveTeam/warrior-dockerfile/issues/56
