### ISSUE TITLE
Request: configure via ENV

### ISSUE THREAD

**Issue by altano** [ArchiveTeam/warrior-dockerfile#73]
Would it be possible to configure a warrior through environment variables instead of going to a webserver on localhost? This would allow a person to configure their warrior in a declarative manner, e.g. via a docker compose file, without ever having to jump into a web server. It would also mean not having to expose a web server, which would reduce the complexity of the warrior (and improve security).

**Comment by berezovskyi** [comment]
I am configuring my instance with these env vars: https://github.com/ArchiveTeam/warrior-dockerfile#configuration-mapping
