### ISSUE TITLE
WARRIOR_ID not honored

### ISSUE THREAD

**Issue by maxiride** [ArchiveTeam/warrior-dockerfile#78]
<s>Every time the container is updated, I loose the configured nickname. Since ENV variables are already available for other application parameters could we have one for the nickname?</s>

The ENV variable WARRIOR_ID, which I assume is for the Nickname option in the WebUI is not honoured. Whatever string is assingned to the variable is not reflected in the Warrior configuration and UI.

**Comment by TheTechRobo** [comment]
I'm pretty sure the environment variable you're looking for is DOWNLOADER

**Comment by maxiride** [comment]
> I'm pretty sure the environment variable you're looking for is DOWNLOADER

Yes, I can confirm the DOWNLOADER ENV sets the nickname.
