### ISSUE TITLE
Specify DNS Servers

### ISSUE THREAD

**Issue by raybooysen** [ArchiveTeam/warrior-dockerfile#84]
As part of the docker container, the DNS servers are hard-coded.  Is it possible to have the DNS server able to be specified via environment variables?

**Comment by Arkiver2** [comment]
Almost all projects now use Quad9 to resolve domains, no matter what is set elsewhere. If we allow for a change in DNS resolvers, there is a higher chance of wrong data being archived as some resolvers may refuse to handle some domains or resolve them wrong.
